import type { Metadata } from "next";
import { Roboto} from "next/font/google";
import "./globals.css";
import AuthProvider from "./components/AuthProvider";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import SubNavBar from "./components/SubNavBar";

const RobotoSans = Roboto({
  variable: "--font-robo-sans",
  subsets: ["latin"],
  weight:['400','500','600','700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RobotoSans.variable} antialiased bg-background`} suppressHydrationWarning={true}
      >
      <AuthProvider>
        <NavBar/>
        <SubNavBar/>
        {children}
        <Footer/>
      </AuthProvider>
      </body>
    </html>
  );
}
